---
# application.yml
spring:
  oauth2:
    client:
      clientId: client
      clientSecret: secret
      userAuthorizationUri: http://localhost:8080/oauthServer/oauth/authorize
      accessTokenUri: http://localhost:8080/oauthServer/oauth/token
    resource:
      tokenInfoUri: http://localhost:8080/oauthServer/oauth/check_token 

# For some reason, we need to turn basic security off,
# otherwise we will be prompted for credentials unprotected resources.
security.basic.enabled: false     